### ISSUE TITLE
Dialog issues tracker.

### ISSUE THREAD

**Issue by rabbitism** [irihitech/Ursa.Avalonia#134]
- [X] 1. Drawer should impact host modal property, too. 
- [ ] 2. ~~OverlayDialog close button should not be focusable.~~ This is invalid in A11y perspective.  
- [x] 3. Overlay MessageBox should support dragmove. 
- [x] 4. Overlay DialogControl Close button should not be red. 
- [X] 5. Drawer Demo use Global&Modasl&Right as default
- [x] 6. https://github.com/irihitech/Ursa.Avalonia/issues/163
